Repository codingBottle/JMGDH_Server, pull requests merged in 2024-01, with the labels that each got.

#6 OAuth2 로그인, 회원가입 구현
  build.gradle
  src/main/java/com/codingbottle/calendar/domain/auth/attribute/OAuthAttributes.java
  src/main/java/com/codingbottle/calendar/domain/auth/dto/LoginDto.java
  src/main/java/com/codingbottle/calendar/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/codingbottle/calendar/domain/auth/filter/JwtVerificationFilter.java
  src/main/java/com/codingbottle/calendar/domain/auth/handler/MemberAuthenticationFailureHandler.java
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberFailureHandler.java
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/codingbottle/calendar/domain/auth/userdetails/MemberDetailsService.java
  src/main/java/com/codingbottle/calendar/domain/auth/userdetails/OAuth2MemberService.java
  src/main/java/com/codingbottle/calendar/domain/calendardate/entity/CalendarDate.java
  src/main/java/com/codingbottle/calendar/domain/common/BaseEntity.java
  src/main/java/com/codingbottle/calendar/domain/member/controller/MemberController.java
  src/main/java/com/codingbottle/calendar/domain/member/dto/MemberResponseDto.java
  src/main/java/com/codingbottle/calendar/domain/member/entity/Member.java
  src/main/java/com/codingbottle/calendar/domain/member/service/MemberService.java
  src/main/java/com/codingbottle/calendar/domain/redis/RedisService.java
  src/main/java/com/codingbottle/calendar/domain/schedule/entity/Schedule.java
  src/main/java/com/codingbottle/calendar/global/config/RedisConfig.java
  src/main/java/com/codingbottle/calendar/global/config/SecurityConfig.java
  src/main/java/com/codingbottle/calendar/global/exception/common/ErrorCode.java
  src/main/java/com/codingbottle/calendar/global/utils/RandomPasswordGenerator.java
  src/main/resources/application.yaml
Labels: member

#7 [Update] OAuth2 redirect-uri 추가
  src/main/resources/application.yaml
Labels: member

#8 [Fix] OAuth2 redirect-uri 추가
  src/main/resources/application.yaml
Labels: member

#10 [Fix] CI-CD, redirect-uri 수정
  .github/workflows/CI_CD.yml
  src/main/resources/application.yaml
Labels: member

#13 Jaeyong/member
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/resources/application.yaml
Labels: member

#14 [Fix] jwt accessToekn 만료시간 변경
  src/main/resources/application.yaml
Labels: member

#15 구글 캘린더 api 연동
  build.gradle
  src/main/java/com/codingbottle/calendar/domain/auth/filter/JwtVerificationFilter.java
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/codingbottle/calendar/domain/member/controller/GoogleCalendarApiLocalController.java
  src/main/java/com/codingbottle/calendar/domain/member/controller/GoogleCalendarApiServerController.java
  src/main/java/com/codingbottle/calendar/domain/member/controller/MemberController.java
Labels: member

#16 [Fix] CI/CD 수정
  .github/workflows/CI_CD.yml
Labels: member

#25 [Update] member Entity 수정
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/codingbottle/calendar/domain/member/dto/MemberResponseDto.java
  src/main/java/com/codingbottle/calendar/domain/member/entity/Member.java
  src/main/java/com/codingbottle/calendar/domain/member/service/MemberService.java
  src/main/java/com/codingbottle/calendar/global/config/init/InitMember.java
  src/main/java/com/codingbottle/calendar/global/utils/RandomPasswordGenerator.java
Labels: member

#26 Fix. OAuth redirect path 오류 수정
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/codingbottle/calendar/domain/schedule/controller/GoogleCalendarApiLocalController.java
Labels: bug

#28 OAuth 인증 후 일회용 인증코드로 토큰 발급받기
  build.gradle
  src/main/java/com/codingbottle/calendar/domain/auth/cache/OAuthOTUCache.java
  src/main/java/com/codingbottle/calendar/domain/auth/controller/OAuthMemberController.java
  src/main/java/com/codingbottle/calendar/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberFailureHandler.java
  src/main/java/com/codingbottle/calendar/domain/auth/handler/OAuth2MemberSuccessHandler.java
  src/main/java/com/codingbottle/calendar/domain/auth/jwt/JwtTokenizer.java
  src/main/java/com/codingbottle/calendar/domain/member/controller/MemberController.java
  src/main/java/com/codingbottle/calendar/global/config/SecurityConfig.java
  src/main/java/com/codingbottle/calendar/global/test/TestMemberTokenProvider.java
Labels: enhancement
